Update organization registration form
ClearPathNYC/clearpath-web pull request #87
Opened 2023-04-06 05:31 UTC by ayanmallik

## Status:

:rocket: Ready

## Summary

- Modify registration form to align with changes listed in [this doc](https://docs.google.com/document/d/1XSPafJsfpD6KDLOipySdMLaMD3llxXHg7ymWHnZzTDU/edit)
- Shoutout Sophia and Emily for listing everything that needs fixing

## Changes

- Bolden borders around selected category/claim options
- Add field that asks “What resource category best describes your organization?”
- Add field that asks “Does your organization offer in-person resources?”
- Change “Location” to “Street Address”
- Split “Type” field to 2 new fields (uncustomizable multi-select tags)
  - Target Communities Field
  - Additional Resources Field 
    - Delete primary selected resource from additional categories  

## Screenshots

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/45826922/230279925-d5ec187e-2a45-46bd-a1c0-39ad79aa33a9.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/45826922/230279997-c1247a30-53e7-49ca-8bea-66ef09f5b776.png">

2023-04-06 05:59 UTC, em1lyc requested changes
I think you covered everything in the doc, but I think that Sophia and I also left out a couple of things 😭 
- Form validation for resource category since non-profits are required to register a main category
- All fields after the age range should be optional
- Disable borough and street address fields after the user selects no in-person location
- If the user chooses that a location has an in-person location, make borough and street address fields required (add form validation)
- Update summary in the last step with new updates

2023-04-06 06:33 UTC, szhuang21 requested changes
ayan 🪨 s!!! the only big change i noticed (besides +1ing on everything emily said) was the issue ab not all primary categories showing up.

2023-04-06 06:33 UTC, szhuang21 commented on src/components/organization-form-steps/organization-contact-info/index.tsx
> +              />
One thing I noticed with this is that the dropdown only shows categories up to the "Academic Development" category, so it looks like its missing categories like "Legal" and "Career Development". I checked the array of primaryCategoryOptions and it includes everything, so it might just be a scrolling behavior issue? 

<img width="412" alt="Screen Shot 2023-04-06 at 1 19 58 AM" src="https://user-images.githubusercontent.com/44931711/230288342-6f43cd69-3616-46b1-b32a-431ca84f6d2e.png">

<img width="387" alt="Screen Shot 2023-04-06 at 1 20 20 AM" src="https://user-images.githubusercontent.com/44931711/230288392-bf541a38-706c-40fc-92ec-0fafe3dca9ca.png">

2023-04-06 06:33 UTC, szhuang21 commented on src/components/claim-organization/styles.ts
> +    border: 2px solid ${p.theme.colors.border[p.variant]};
CSS god

2023-04-06 06:33 UTC, szhuang21 commented on src/components/organization-form-steps/organization-details/index.tsx
> +  ];
wow! very organized! very tech lead! go ayan! no pineapples

2023-04-06 17:17 UTC, ayanmallik commented on src/components/organization-form-steps/organization-contact-info/index.tsx
> +              />
Yeah the scroll behavior in geneal is just super clunky, will try to resolve it here!

2023-04-06 17:46 UTC, ayanmallik commented on src/components/organization-form-steps/organization-details/index.tsx
> +  ];
thx for confirming no pineapple 🍍

2023-04-08 18:16 UTC, em1lyc approved these changes
lg(e)tm

2023-04-08 18:18 UTC, szhuang21 approved these changes

2023-04-08 19:13 UTC, merged